In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [4]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [16]:
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
rand(4)

NameError: name 'rand' is not defined

In [20]:
random.rand(4)

NameError: name 'random' is not defined

In [21]:
np.random.rand(4)

array([0.68763143, 0.59201844, 0.2831625 , 0.4126911 ])

In [22]:
np.random.rand(2,2)

array([[0.60418063, 0.89790482],
       [0.85569614, 0.62949433]])

In [23]:
np.random.randint(3)

0

In [24]:
np.random.randint(0,3)

1

In [25]:
np.random.randint(10,15)

13

In [26]:
np.random.randint(1,5,3)

array([2, 3, 4], dtype=int32)

In [27]:
np.random.randint(1,2,4)

array([1, 1, 1, 1], dtype=int32)

In [28]:
np.random.randint(1,5,2)

array([1, 2], dtype=int32)

In [29]:
np.random.randint(5,2,3)

ValueError: low >= high

In [30]:
np.random.randint(-5,2,3)

array([-2,  0, -1], dtype=int32)

In [31]:
np.random.randint(-5,2,3)

array([-2, -3,  1], dtype=int32)

In [32]:
np.random.randint(10,40,(10,10))

array([[24, 21, 30, 16, 15, 12, 18, 29, 33, 24],
       [22, 33, 11, 30, 35, 34, 11, 36, 19, 39],
       [13, 22, 30, 38, 24, 18, 23, 27, 18, 20],
       [22, 12, 27, 23, 13, 17, 25, 11, 14, 16],
       [15, 24, 36, 19, 27, 10, 32, 33, 20, 26],
       [20, 36, 18, 38, 12, 34, 19, 35, 34, 21],
       [24, 16, 12, 12, 10, 17, 27, 10, 16, 17],
       [35, 34, 26, 26, 31, 36, 16, 10, 12, 20],
       [36, 15, 16, 33, 37, 39, 24, 20, 33, 17],
       [34, 24, 28, 28, 13, 28, 31, 12, 12, 21]], dtype=int32)

In [33]:
ri=np.random.randint(10,40,(10,10))
ri

array([[16, 30, 34, 10, 25, 24, 16, 38, 13, 22],
       [24, 14, 10, 24, 37, 14, 32, 29, 33, 16],
       [17, 39, 26, 10, 32, 33, 14, 20, 10, 39],
       [16, 37, 13, 21, 19, 27, 10, 29, 25, 22],
       [23, 18, 22, 23, 17, 36, 30, 21, 38, 18],
       [28, 25, 34, 11, 30, 38, 34, 23, 24, 35],
       [16, 15, 17, 14, 14, 34, 17, 25, 32, 19],
       [24, 16, 22, 32, 10, 17, 19, 35, 37, 14],
       [34, 15, 39, 19, 24, 13, 21, 15, 32, 13],
       [13, 37, 22, 25, 22, 23, 23, 38, 20, 26]], dtype=int32)

In [34]:
len(ri)

10

In [35]:
ri=np.random.randint(10,40,(3,5))
ri

array([[33, 22, 24, 23, 37],
       [12, 19, 27, 28, 10],
       [21, 11, 34, 23, 38]], dtype=int32)

In [36]:
len(ri)

3

In [37]:
ri.shape

(3, 5)

In [38]:
id(ri)

2230589163056

In [39]:
ri

array([[33, 22, 24, 23, 37],
       [12, 19, 27, 28, 10],
       [21, 11, 34, 23, 38]], dtype=int32)

slicing in numpy

In [40]:
ri[:]

array([[33, 22, 24, 23, 37],
       [12, 19, 27, 28, 10],
       [21, 11, 34, 23, 38]], dtype=int32)

In [41]:
ri[1]

array([12, 19, 27, 28, 10], dtype=int32)

In [42]:
ri[0:3]

array([[33, 22, 24, 23, 37],
       [12, 19, 27, 28, 10],
       [21, 11, 34, 23, 38]], dtype=int32)

In [43]:
ri_1=np.random.randint(10,40,(10,10))
ri_1

array([[24, 29, 16, 14, 13, 38, 19, 30, 27, 23],
       [17, 33, 38, 21, 27, 22, 15, 38, 27, 30],
       [12, 33, 28, 34, 25, 25, 32, 36, 38, 25],
       [30, 27, 16, 27, 38, 30, 35, 16, 16, 16],
       [36, 39, 23, 10, 20, 18, 31, 36, 20, 39],
       [24, 15, 33, 34, 25, 35, 32, 17, 27, 17],
       [14, 22, 11, 38, 37, 13, 36, 23, 22, 33],
       [38, 24, 28, 21, 26, 21, 13, 22, 28, 37],
       [22, 23, 10, 21, 19, 27, 26, 29, 22, 17],
       [16, 27, 35, 35, 16, 16, 35, 38, 27, 11]], dtype=int32)

In [44]:
ri_1.shape

(10, 10)

In [45]:
ri_1=np.random.randint(10,40,(10,10))
print(ri_1)

[[12 15 19 25 25 38 10 23 24 19]
 [19 15 11 23 33 19 35 18 31 11]
 [25 39 24 33 20 30 25 21 11 23]
 [26 32 39 38 34 28 29 34 16 23]
 [19 27 28 34 34 11 23 16 34 28]
 [32 31 36 28 13 36 19 33 37 36]
 [27 27 18 32 36 24 16 27 11 11]
 [23 31 21 29 16 18 36 36 17 24]
 [39 19 23 16 25 24 38 15 25 14]
 [31 20 27 24 24 19 11 32 10 22]]


In [46]:
ri_1.shape

(10, 10)

In [47]:
ri_1

array([[12, 15, 19, 25, 25, 38, 10, 23, 24, 19],
       [19, 15, 11, 23, 33, 19, 35, 18, 31, 11],
       [25, 39, 24, 33, 20, 30, 25, 21, 11, 23],
       [26, 32, 39, 38, 34, 28, 29, 34, 16, 23],
       [19, 27, 28, 34, 34, 11, 23, 16, 34, 28],
       [32, 31, 36, 28, 13, 36, 19, 33, 37, 36],
       [27, 27, 18, 32, 36, 24, 16, 27, 11, 11],
       [23, 31, 21, 29, 16, 18, 36, 36, 17, 24],
       [39, 19, 23, 16, 25, 24, 38, 15, 25, 14],
       [31, 20, 27, 24, 24, 19, 11, 32, 10, 22]], dtype=int32)

In [48]:
ri_1[:]

array([[12, 15, 19, 25, 25, 38, 10, 23, 24, 19],
       [19, 15, 11, 23, 33, 19, 35, 18, 31, 11],
       [25, 39, 24, 33, 20, 30, 25, 21, 11, 23],
       [26, 32, 39, 38, 34, 28, 29, 34, 16, 23],
       [19, 27, 28, 34, 34, 11, 23, 16, 34, 28],
       [32, 31, 36, 28, 13, 36, 19, 33, 37, 36],
       [27, 27, 18, 32, 36, 24, 16, 27, 11, 11],
       [23, 31, 21, 29, 16, 18, 36, 36, 17, 24],
       [39, 19, 23, 16, 25, 24, 38, 15, 25, 14],
       [31, 20, 27, 24, 24, 19, 11, 32, 10, 22]], dtype=int32)

In [49]:
ri_1[3:8]

array([[26, 32, 39, 38, 34, 28, 29, 34, 16, 23],
       [19, 27, 28, 34, 34, 11, 23, 16, 34, 28],
       [32, 31, 36, 28, 13, 36, 19, 33, 37, 36],
       [27, 27, 18, 32, 36, 24, 16, 27, 11, 11],
       [23, 31, 21, 29, 16, 18, 36, 36, 17, 24]], dtype=int32)

In [50]:
ri_1[3,8]

np.int32(16)

In [51]:
ri_1[-5]

array([32, 31, 36, 28, 13, 36, 19, 33, 37, 36], dtype=int32)

In [52]:
ri_1[-5,-3]

np.int32(33)

In [53]:
print(ri_1[-5,-3])

33


In [54]:
ri_1[::3]

array([[12, 15, 19, 25, 25, 38, 10, 23, 24, 19],
       [26, 32, 39, 38, 34, 28, 29, 34, 16, 23],
       [27, 27, 18, 32, 36, 24, 16, 27, 11, 11],
       [31, 20, 27, 24, 24, 19, 11, 32, 10, 22]], dtype=int32)

In [55]:
ri_1

array([[12, 15, 19, 25, 25, 38, 10, 23, 24, 19],
       [19, 15, 11, 23, 33, 19, 35, 18, 31, 11],
       [25, 39, 24, 33, 20, 30, 25, 21, 11, 23],
       [26, 32, 39, 38, 34, 28, 29, 34, 16, 23],
       [19, 27, 28, 34, 34, 11, 23, 16, 34, 28],
       [32, 31, 36, 28, 13, 36, 19, 33, 37, 36],
       [27, 27, 18, 32, 36, 24, 16, 27, 11, 11],
       [23, 31, 21, 29, 16, 18, 36, 36, 17, 24],
       [39, 19, 23, 16, 25, 24, 38, 15, 25, 14],
       [31, 20, 27, 24, 24, 19, 11, 32, 10, 22]], dtype=int32)

In [56]:
ri_1[::1]

array([[12, 15, 19, 25, 25, 38, 10, 23, 24, 19],
       [19, 15, 11, 23, 33, 19, 35, 18, 31, 11],
       [25, 39, 24, 33, 20, 30, 25, 21, 11, 23],
       [26, 32, 39, 38, 34, 28, 29, 34, 16, 23],
       [19, 27, 28, 34, 34, 11, 23, 16, 34, 28],
       [32, 31, 36, 28, 13, 36, 19, 33, 37, 36],
       [27, 27, 18, 32, 36, 24, 16, 27, 11, 11],
       [23, 31, 21, 29, 16, 18, 36, 36, 17, 24],
       [39, 19, 23, 16, 25, 24, 38, 15, 25, 14],
       [31, 20, 27, 24, 24, 19, 11, 32, 10, 22]], dtype=int32)

In [57]:
ri_1[::-5]

array([[31, 20, 27, 24, 24, 19, 11, 32, 10, 22],
       [19, 27, 28, 34, 34, 11, 23, 16, 34, 28]], dtype=int32)

In [58]:
ri_1[2]

array([25, 39, 24, 33, 20, 30, 25, 21, 11, 23], dtype=int32)

In [59]:
ri_1[:,2]

array([19, 11, 24, 39, 28, 36, 18, 21, 23, 27], dtype=int32)

In [60]:
print(ri_1[2])
print(ri_1[:,2])

[25 39 24 33 20 30 25 21 11 23]
[19 11 24 39 28 36 18 21 23 27]


In [61]:
ri_1[:,-8]

array([19, 11, 24, 39, 28, 36, 18, 21, 23, 27], dtype=int32)

In [62]:
ri_1[2:6,3:5]

array([[33, 20],
       [38, 34],
       [34, 34],
       [28, 13]], dtype=int32)

In [63]:
ri_1[2:8,3:8]

array([[33, 20, 30, 25, 21],
       [38, 34, 28, 29, 34],
       [34, 34, 11, 23, 16],
       [28, 13, 36, 19, 33],
       [32, 36, 24, 16, 27],
       [29, 16, 18, 36, 36]], dtype=int32)

In [64]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [67]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [69]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

# numpy masking of filter

In [70]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [71]:
id(mat)

2230589317136

In [72]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [74]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [75]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [76]:
mat[mat==50]

array([50])

In [77]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [78]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [79]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [80]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [81]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [82]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [83]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [84]:
a4=mat[mat==50]
a4

array([50])

In [93]:
import random
def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp =''.join(random.choice(digits)for _ in range(length))
    return otp
otp_length=4
otp=generate_otp(otp_length)
print(f"your otp is:{otp}")

your otp is:1300


# Assistant
The error occurs because of a syntax issue in your code. There are actually a few issues to fix:

1. In line 7, you have `otp-length=4` which is trying to subtract `length` from `otp` and then assign the result to something. This is invalid syntax.
2. In the `generate_otp` function, you're using `digit` in the loop but defined `digits` (with an 's').
3. There's no space after the first equal sign in the f-string.

Would you like me to provide the corrected code?

# Assistant
The error occurs due to several syntax issues in your code. Let me explain:

1. In the line `otp=''.join(random.choice(digit)for_in range(length))`, there are multiple issues:
   - `digit` should be `digits` (the variable you defined)
   - `for_in` should be `for _ in` (missing space and underscore)

2. In the line `otp-length=4`, you're using a hyphen instead of an underscore for the variable name.

Would you like me to provide the corrected code?

# Assistant
The error occurs due to several syntax issues in your code. Let me explain:

1. In the line `otp=''.join(random.choice(digit)for_in range(length))`, there are multiple issues:
   - `digit` should be `digits` (the variable you defined)
   - `for_in` should be `for _ in` (missing space and underscore)

2. In the line `otp-length=4`, you're using a hyphen instead of an underscore for the variable name.

Would you like me to provide the corrected code?

In [91]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 1024


In [94]:
def wish():
    print('good even')
wish()
def wish():
    print('good even')
wish()
def wish():
    print('good even')
wish()

good even
good even
good even


In [95]:
def wish():
    print('good even')
wish()
wish()
wish()

good even
good even
good even


In [ ]:
list1=['a','b','g',1,5