In [4]:
import numpy as np

In [5]:
a=np.array([1,2,3,4])
print("array a:",a)

array a: [1 2 3 4]


In [6]:
b=np.arange(0,10,2)
print("array b:",b)

array b: [0 2 4 6 8]


In [7]:
b=np.arange(0,10,3)
print("array b:",b)

array b: [0 3 6 9]


In [8]:
d=np.zeros((2,3))
print("array d:\n",d)

array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
e=np.ones((3,2))
print("array e:\n",e)

array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
f=np.eye(4)
print("identity matrix f:\n",f)

identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Array manipulation functions

In [11]:
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3))
print("reshaped array:",reshaped)

reshaped array: [[1 2 3]]


In [12]:
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1))
print("reshaped array:",reshaped)

reshaped array: [[1]
 [2]
 [3]]


In [13]:
f1=np.array([[1,2],[3,4],[5,6],[7,8]])
flattened=np.ravel(f1)
print("falttened array:",flattened)

falttened array: [1 2 3 4 5 6 7 8]


In [14]:
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1)
print("transposed array:\n",transposed)

transposed array:
 [[1 3]
 [2 4]]


In [15]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2])
print("stacked array:\n",stacked)

stacked array:
 [[1 2]
 [3 4]]


In [16]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.hstack([a2,b2])
print("stacked array:\n",stacked)

stacked array:
 [1 2 3 4]


In [17]:
g=np.array([1,2,3,4])
added=np.add(g,2)
print("added 2 to g:",added)

added 2 to g: [3 4 5 6]


In [18]:
squared=np.power(g,2)
print("squared g:",squared)

squared g: [ 1  4  9 16]


In [19]:
sqrt_val=np.sqrt(g)
print("square root g:",sqrt_val)

square root g: [1.         1.41421356 1.73205081 2.        ]


In [20]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [21]:
a3=np.array([1,2,3])
dot_product=np.dot(a,g)
print("dot product of a1 and g:",dot_product)

dot product of a1 and g: 30


In [22]:
print(a)
print(a1)

[1 2 3 4]
[1 2 3]


In [23]:
s=np.array([1,2,3,4])
mean=np.mean(s)
print("mean of s:",mean)

mean of s: 2.5


In [24]:
std_dev=np.std(s)
print("standard deviation of s:",std_dev)

standard deviation of s: 1.118033988749895


In [25]:
minimum=np.min(s)
print("mim of s:",minimum)

mim of s: 1


In [26]:
maximum=np.max(s)
print("max of s:",maximum)

max of s: 4


In [27]:
var=np.var(s)
print("varaiance of s:",var)

varaiance of s: 1.25


# random sampling functions

In [28]:
random_vals=np.random.rand(3)
print("random values:",random_vals)

random values: [0.12322495 0.79770721 0.09375236]


In [29]:
np.random.seed(0)
random_vals=np.random.rand(3)
print("random values:",random_vals)

random values: [0.5488135  0.71518937 0.60276338]


In [30]:
rand_int=np.random.randint(0,10,size=5)
print("random integers:",rand_int)

random integers: [3 7 9 3 5]


In [31]:
np.random.seed(0)
rand_int=np.random.randint(0,10,size=5)
print("random integers:",rand_int)

random integers: [5 0 3 3 7]


#boolean & logical functions

In [33]:
logical_test=np.array([True,False,True])
all_True=np.all(logical_test)
print("all elements True:",all_True)

all elements True: False


In [34]:
logical_test=np.array([False,False,False])
all_true=np.all(logical_test)
print("all elements True:",all_true)

all elements True: False


In [35]:
any_true=np.any(logical_test)
print("any elements True;",any_true)

any elements True; False


8.set operations

In [36]:
set_a=np.array([1,2,3,4])
set_b=np.array([3,4,5,6])
intersection=np.intersect1d(set_a,set_b)
print("intersection of a and b:",intersection)

intersection of a and b: [3 4]


In [37]:
union=np.union1d(set_a,set_b)
print("union of a and b:",union)

union of a and b: [1 2 3 4 5 6]


###9.Array Attribute Functions

In [41]:
a=np.array([1,2,3])
shape=a.shape
size=a.size
dimensions=a.ndim
dtype=a.dtype
print("shape of a:",shape)
print("size of a:",size)
print("number of dimensions of a:",dimensions)
print("data type of a:",dtype)
      

shape of a: (3,)
size of a: 3
number of dimensions of a: 1
data type of a: int64


10.Other Data types

In [42]:
a=np.array([1,2,3])
copied_array=np.copy(a)
print("copied array:",copied_array)

copied array: [1 2 3]


In [45]:
array_size_in_bytes=a.nbytes
print("size of a in bytes:",array_size_in_bytes)

size of a in bytes: 24


In [50]:
shared=np.shares_memory(a,copied_array)
print("do a and copied_array share memory?",shared)

do a and copied_array share memory? False
